<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.dtx</string>
	</array>
	<key>firstLineMatch</key>
	<string>^%\s*\\iffalse\s+(?:meta-)?comment</string>
	<key>name</key>
	<string>LaTeX Documented Source</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(%)(?:    (\\begin){macrocode}|(&lt;\*)([A-Za-z0-9!\|]+|.)(&gt;))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.tex.latex.dtx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.punctuation.selection.tex.latex.dtx</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.selection.tex.latex.dtx</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.punctuation.selection.tex.latex.dtx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(%)(?:    (\\end){macrocode}|(&lt;/)(\4)(&gt;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.tex.latex.dtx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.punctuation.selection.tex.latex.dtx</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.selection.tex.latex.dtx</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.punctuation.selection.tex.latex.dtx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.tex.latex.dtx.implementation</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.tex.latex.dtx</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.punctuation.selection.tex.latex.dtx</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.selection.tex.latex.dtx</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.punctuation.selection.tex.latex.dtx</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(%)(&lt;[\*/]?)([A-Za-z0-9!\|]+|.)(&gt;)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.be</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:\{|\s*(\\begin)\{.+\})</string>
					<key>name</key>
					<string>meta.disabled.scopes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^(%).*\\(?:begin|end){macrocode}</string>
			<key>name</key>
			<string>invalid.illegal.markup.tex.latex.dtx</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.tex.latex.dtx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.punctuation.selection.tex.latex.dtx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.selection.tex.latex.dtx</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.punctuation.selection.tex.latex.dtx</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(%)(&lt;[\*/]?)([A-Za-z0-9!\|]+|.)(&gt;)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^%</string>
			<key>name</key>
			<string>comment.block.tex.latex.dtx</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\CharacterTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!\\)}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^%</string>
					<key>name</key>
					<string>comment.block.tex.latex.dtx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>markup.raw.charactertable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.dtx</string>
	<key>uuid</key>
	<string>2C03C6B8-9EF6-4087-BA82-E1EF72BF153B</string>
</dict>
</plist>
